//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int sellerID { get; set; }
        public string sellerName { get; set; }
        public string sellerPassword { get; set; }
    }
}
